from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent
DATA_DIR = PROJECT_ROOT / "data"
RESULTS_DIR = PROJECT_ROOT / "results"
EXPLANATION_RESULTS_DIR = RESULTS_DIR / "explanation"
PLOTS_RESULTS_DIR = RESULTS_DIR / "plots"
LATEST_RESULTS_DIR = RESULTS_DIR / "latest"
SCRATCH_RESULTS_DIR = RESULTS_DIR / "scratch"
TUNING_RESULTS_DIR = RESULTS_DIR / "tuning"
DOCS_DIR = PROJECT_ROOT / "docs"
LEGACY_DIR = PROJECT_ROOT / "legacy"
LEGACY_DATA_ARCHIVE_DIR = LEGACY_DIR / "data_archive"
EXTERNAL_DATA_DIR = DATA_DIR / "external"
STANDARDIZED_DATA_DIR = DATA_DIR / "standardized"
RAW_DATA_DIR = DATA_DIR / "raw"
CCLE_DATA_DIR = STANDARDIZED_DATA_DIR / "CCLE"
GDSC_DATA_DIR = STANDARDIZED_DATA_DIR / "GDSC"
CGP_DATA_DIR = RAW_DATA_DIR / "CGP"
CCLE_EXTERNAL_DATA_DIR = EXTERNAL_DATA_DIR / "CCLE"
GDSC_EXTERNAL_DATA_DIR = EXTERNAL_DATA_DIR / "GDSC"
CGP_EXTERNAL_DATA_DIR = EXTERNAL_DATA_DIR / "CGP"
CCLE_STANDARDIZED_DIR = CCLE_DATA_DIR
GDSC_STANDARDIZED_DIR = GDSC_DATA_DIR
CGP_STANDARDIZED_DIR = STANDARDIZED_DATA_DIR / "CGP"
CCLE_RAW_DATA_DIR = RAW_DATA_DIR / "CCLE"
GDSC_RAW_DATA_DIR = RAW_DATA_DIR / "GDSC"
CGP_RAW_DATA_DIR = CGP_DATA_DIR
